services:
    Vangrg\ProfanityBundle\Storage\ProfanitiesStorageDefault: @vangrg_profanity.storage.default
    vangrg_profanity.storage.default:
        class: Vangrg\ProfanityBundle\Storage\ProfanitiesStorageDefault
        arguments:
            - "%vangrg_profanity.source.file_name%"
            - "%vangrg_profanity.source.format%"

    Vangrg\ProfanityBundle\Service\ProfanityChecker: @vangrg_profanity.checker
    vangrg_profanity.checker:
        class: Vangrg\ProfanityBundle\Service\ProfanityChecker
        arguments:
            - "@vangrg_profanity.storage"
            - '%vangrg_profanity.allow_bound_by_words%'

    Vangrg\ProfanityBundle\Validator\Constraints\ProfanityCheckValidator: @vangrg_profanity.profanity_check_validator
    vangrg_profanity.profanity_check_validator:
        class: Vangrg\ProfanityBundle\Validator\Constraints\ProfanityCheckValidator
        arguments:
            - '@vangrg_profanity.checker'
        tags:
            - { name: validator.constraint_validator }
