services:
    vangrg_profanity.storage:
        class: Vangrg\ProfanityBundle\Storage\ProfanitiesStorage

    vangrg_profanity.check:
        class: Vangrg\ProfanityBundle\Service\Check
        arguments: ["@vangrg_profanity.storage"]
