services:
    vangrg_profanity.storage:
        class: %vangrg_profanity.storage_class%

    vangrg_profanity.check:
        class: Vangrg\ProfanityBundle\Service\Check
        arguments: ["@vangrg_profanity.storage"]

    vangrg_profanity.profanity_check_validator:
        class: Vangrg\ProfanityBundle\Validator\Constraints\ProfanityCheckValidator
        arguments:
            - '@vangrg_profanity.check'
        tags:
            - { name: validator.constraint_validator }
