services:
    vangrg_profanity.storage:
        class: %vangrg_profanity.storage_class%

    vangrg_profanity.check:
        class: Vangrg\ProfanityBundle\Service\Check
        arguments: ["@vangrg_profanity.storage"]
